application: amoulyweb
version: 1
runtime: go
api_version: go1

handlers:

- url: /templates/css
  static_dir: static/templates/css

- url: /templates/bitmaps
  static_dir: static/templates/bitmaps

- url: /.*
  script: _go_app
 

